### PR TITLE
Update git diff logic

### PR DESCRIPTION
**Pull request by sallyom**
* update git logic to Fetch, Checkout
* save each method's last known commit - that might be different for each method listed per repository
* filter git changes per method  in the findDiff function
* cleanup
* add workflow for addition of files to fileTransfer method
(I also tested addition of a color3 pod/file locally)

### CODE REVIEW

**Comment by sallyom** [comment]
@josephsawaya do you think this will help?

**Comment by josephsawaya** [comment]
The fetch and reset part in findDiff looks good to me right now

**Comment by sallyom** [comment]
um, this is working I do believe - maybe there is a simpler way, but for now, this is working, wooot

**Comment by cooktheryan** [comment]
It will be nice to have the commit id

**Comment by sallyom** [comment]
@cooktheryan @josephsawaya The fetch & force-checkout is working well - I've tried removing commits, squashing, etc and AFAICT the program doesn't get tripped up. We might not need the force-re-clone flow, and if we do for some edge case it will be rarely used. These changes are looking good to me :) - Each method's last known commit is saved and changes are compared from the latest commit to the last known one each time that method is processed.

**Review by josephsawaya — APPROVED** [review]

**Pull request merged**
